### ISSUE TITLE
Suitcase errors on selecting reset option while download is in progress

### ISSUE THREAD

**Issue by Shubhamr837** [odk-x/tool-suite-X#219]
**Software and hardware versions**
ODK-X Suitcase v2.1.7

**Problem description**
Suitcase logs an error Message if Reset option is clicked from the upload tab in GUI while download is in progress . This happens because files get deleted while being downloaded.

error message for table_id "geotagger" :
`java.lang.IllegalArgumentException: tableId: geotagger does not exist
	at org.opendatakit.suitcase.net.SyncWrapper.batchGetFilesForRow(SyncWrapper.java:261)
	at org.opendatakit.suitcase.net.AttachmentManager.downloadAttachments(AttachmentManager.java:123)
	at org.opendatakit.suitcase.model.ODKCsv.getData(ODKCsv.java:533)
	at org.opendatakit.suitcase.model.ODKCsv.get(ODKCsv.java:308)
	at org.opendatakit.suitcase.model.ODKCsv$ODKCSVIterator.next(ODKCsv.java:48)
	at org.opendatakit.suitcase.net.DownloadTask.doInBackground(DownloadTask.java:89)
	at org.opendatakit.suitcase.net.DownloadTask.doInBackground(DownloadTask.java:23)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)`

Steps to reproduce the problem

Open suitcase and login.
Enter a table_id to download , check the download attachments option as true ( This results in download taking more time ) and click download .
Select Reset from the Upload tab while download is in progress. Wait for the reset operation to complete. Just after reset operation is complete , error will be displayed in the log .

Possible solution could be to disable the reset button while another operation is being performed.

**Comment by wbrunette** [comment]
@Shubhamr837 you are correct. This is a bug. Did you want to work on this or are you simply reporting it?

**Comment by Shubhamr837** [comment]
@wbrunette Thanks. I would like to work on this. Could you please assign this to me .

**Comment by wbrunette** [comment]
@Shubhamr837 I have assigned the issue to you. Thanks for finding and fixing.
