### ISSUE TITLE
Suitcase errors on downloading with "apply scan formatting" option checked as true .

### ISSUE THREAD

**Issue by Shubhamr837** [odk-x/tool-suite-X#220]
Suitcase shows error while downloading with "apply scan formatting" option checked as true.
This happens with the test data (https://github.com/odk-x/suitcase/tree/master/testfiles/dataToUpload) uploaded in the cloud endpoint server
.
**version** : 2.1.7
**Server url** : http://130.211.209.167:80
**uploaded table** (From the test files in the suitcase repository) : https://github.com/odk-x/suitcase/tree/master/testfiles/dataToUpload

**Error message in log :**
`org.apache.wink.json4j.JSONException: Expecting '{' on line 1, column 227 instead, obtained token: 'Token: String - 'No file found for: http://130.211.209.167:80/odktables/default/tables/geotagger/ref/uuid:b7c3ffa0-8eb8-4c0f-b9f6-efa7a7729f10/attachments/86034682-580e-42c2-ad62-f354f8ff7e63/file/raw_86034682_580e_42c2_ad62_f354f8ff7e63.json''
	at org.apache.wink.json4j.internal.Parser.parseObject(Parser.java:193)
	at org.apache.wink.json4j.internal.Parser.parse(Parser.java:130)
	at org.apache.wink.json4j.JSONObject.<init>(JSONObject.java:193)
	at org.opendatakit.suitcase.model.ScanJson.buildLabelValuePair(ScanJson.java:30)
	at org.opendatakit.suitcase.model.ScanJson.<init>(ScanJson.java:23)
	at org.opendatakit.suitcase.model.ODKCsv.getData(ODKCsv.java:486)
	at org.opendatakit.suitcase.model.ODKCsv.get(ODKCsv.java:308)
	at org.opendatakit.suitcase.model.ODKCsv$ODKCSVIterator.next(ODKCsv.java:48)
	at org.opendatakit.suitcase.net.DownloadTask.doInBackground(DownloadTask.java:89)
	at org.opendatakit.suitcase.net.DownloadTask.doInBackground(DownloadTask.java:23)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Steps to reproduce** :
1 ) open suitcase and login
2 ) upload the test data from the suitcase repository (https://github.com/odk-x/suitcase/tree/master/testfiles/dataToUpload).
3 ) download the table id = geotagger with "apply scan formatting" option checked as true .
4 ) View the logs . There would be multiple errors thrown for file not found in the server .

**Comment by linl33** [comment]
@Shubhamr837 That option only works when the table has been configured for ODK-X Scan. If you're interested in improving the error message, please let me know so I can assign this issue to you.

**Comment by Shubhamr837** [comment]
Thanks @linl33 I would like to work on this issue . Can I you please provide me more details on how is table configured for odk-x scan?

**Comment by linl33** [comment]
For this issue, it would be sufficient for Suitcase to identify that the selected table is missing the required column/attachment and convey such to the user.

If you want to read more about Scan, see https://docs.odk-x.org/scan-form-designer-intro/
