### ISSUE TITLE
Crash in SyncFragment in Services

### ISSUE THREAD

**Issue by linl33** [odk-x/tool-suite-X#221]
SyncFragment crashes after screen rotation while about screen is open.

## Steps to reproduce
1. Open Services
2. Click sync
3. Open about
4. Rotate screen
5. Rotate screen back to the original orientation
6. Crash

## Stacktrace
```
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.opendatakit.sync.service.SyncAttachmentState.name()' on a null object reference
        at org.opendatakit.services.sync.actions.fragments.SyncFragment.onSaveInstanceState(SyncFragment.java:107)
        at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:3140)
        at androidx.fragment.app.FragmentStateManager.saveBasicState(FragmentStateManager.java:683)
        at androidx.fragment.app.FragmentStateManager.saveState(FragmentStateManager.java:649)
        at androidx.fragment.app.FragmentStore.saveActiveFragments(FragmentStore.java:177)
        at androidx.fragment.app.FragmentManager.saveAllState(FragmentManager.java:2653)
        at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:152)
        at androidx.fragment.app.FragmentActivity$1.saveState(FragmentActivity.java:133)
        at androidx.savedstate.SavedStateRegistry.performSave(SavedStateRegistry.java:227)
        at androidx.savedstate.SavedStateRegistryController.performSave(SavedStateRegistryController.java:74)
        at androidx.activity.ComponentActivity.onSaveInstanceState(ComponentActivity.java:310)
        at androidx.appcompat.app.AppCompatActivity.onSaveInstanceState(AppCompatActivity.java:544)
        at org.opendatakit.services.sync.actions.activities.AbsSyncBaseActivity.onSaveInstanceState(AbsSyncBaseActivity.java:180)
        at android.app.Activity.performSaveInstanceState(Activity.java:1496)
        at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1386)
        at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4721)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4672)
        at android.app.ActivityThread.-wrap18(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

```

**Comment by VarunT11** [comment]
@linl33 Can I work on this Issue?

**Comment by linl33** [comment]
@VarunT11 Please finish the 2 other issues assigned to you first. We try to make sure people don't work on too many issues at the same time so there are enough to go around.

**Comment by pawanharariya** [comment]
@linl33 I would like to work on this?

**Comment by riturajjain2000** [comment]
Can I work on this?

**Comment by wbrunette** [comment]
I am going to assign this to @pawanharariya since it's a bug likely related to his changes.
